---
    - name: copy index.html into ngix server
      template: 
	         src=templates/index.html.j2 
			 dest=/var/www/html/index.html
      register: copy_status
      notify: restart ngix server